export const styles = {
    container: "min-h-screen bg-gray-100 text-gray-900",
    header: "bg-gradient-to-r from-blue-500 to-40% to-purple-600 p-4 text-white shadow-md",
    title: "text-2xl font-bold",
    subtitle: "text-sm opacity-80",
    card: "bg-white rounded-lg shadow-md hover:shadow-lg transition-shadow duration-300 overflow-hidden cursor-pointer",
    cardHeader: "p-4 bg-gray-50 border-b",
    cardTitle: "font-semibold text-lg",
    cardDescription: "text-sm text-gray-600",
    cardBody: "p-4",
    button: "flex items-center justify-center rounded-md px-4 py-2 font-medium transition-colors duration-200 cursor-pointer",
    primaryButton: "bg-blue-500 hover:bg-blue-600 text-white",
    secondaryButton: "bg-gray-200 hover:bg-gray-300 text-gray-800",
    dangerButton: "bg-red-500 hover:bg-red-600 text-white",
    progressBar: "h-2 rounded-full bg-gray-200 overflow-hidden",
    progressBarFill: "h-full rounded-full",
    input: "w-full border border-gray-300 rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500",
    badge: "inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium",
    gridLayout: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4",
};